name: Update Dependencies

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true

      - name: Update dependencies
        run: |
          go get -u ./...
          go mod tidy

      - name: Run tests
        run: |
          go install github.com/vektra/mockery/v3@v3.5.5
          mockery
          go test -v ./pkg/...

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update Go dependencies'
          title: 'chore: update Go dependencies'
          body: |
            This PR updates Go dependencies to their latest versions.
            
            Changes:
            - Updated all Go modules to latest versions
            - Ran `go mod tidy` to clean up dependencies
            - All tests pass with updated dependencies
            
            Auto-generated by GitHub Actions.
          branch: chore/update-dependencies
          delete-branch: true
